set(console_bridge_INCLUDE_PATH PATHS "${ROS_EXTERNAL_DEPS_INSTALL}/usr/include" NO_DEFAULT_PATH)
set(console_bridge_LIBRARY_PATH PATHS "${ROS_EXTERNAL_DEPS_INSTALL}/${CPUVARDIR}/usr/lib" NO_DEFAULT_PATH)
find_path(console_bridge_INCLUDE_DIR NAMES console.h PATH_SUFFIXES "console_bridge" ${console_bridge_INCLUDE_PATH})
find_library(console_bridge_LIBRARY  NAMES console_bridge ${console_bridge_LIBRARY_PATH})
if(console_bridge_INCLUDE_DIR)
  if (console_bridge_LIBRARY)
    set(console_bridge_FOUND 1)
  endif()
endif()
set(console_bridge_INCLUDE_DIRS ${console_bridge_INCLUDE_DIR})
set(console_bridge_LIBRARIES ${console_bridge_LIBRARY})
if(console_bridge_FOUND)
  if(NOT TARGET console_bridge::console_bridge)
    add_library(console_bridge::console_bridge UNKNOWN IMPORTED)
    set_property(TARGET console_bridge::console_bridge PROPERTY IMPORTED_LOCATION ${console_bridge_LIBRARY})
    set_property(TARGET console_bridge::console_bridge PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${console_bridge_INCLUDE_DIR})
  endif()
  list(APPEND console_bridge_TARGETS console_bridge::console_bridge)
elseif(console_bridge_FIND_REQUIRED)
  message(FATAL_ERROR "Unable to find console_bridge")
endif()
